
version: "3"

services:
  lora-gateway-bridge:
    build: ./lora-gateway-bridge
    ports: 
      - "1700:1700/udp"
    environment:
      - MQTT_SERVER=tcp://mqtt:1883

  loraserver:
    build: ./loraserver
    links:
      - postgres
      - mqtt
      - redis
      - lora-app-server
    environment:
      - NET_ID=010203
      - BAND=EU_433
      - DB_AUTOMIGRATE=true
      - POSTGRES_DSN=postgres://loraserver:loraserver@postgres/loraserver?sslmode=disable
      - GW_MQTT_SERVER=tcp://mqtt:1883
      - REDIS_URL=redis://redis:6379
      - AS_SERVER=lora-app-server:8001

  lora-app-server:
    build: ./lora-app-server
    links:
      - postgres
      - mqtt
    environment:
      - DB_AUTOMIGRATE=true
      - POSTGRES_DSN=postgres://loraappserver:loraappserver@postgres/loraappserver?sslmode=disable
      - MQTT_SERVER=tcp://mqtt:1883
      - REDIS_URL=redis://redis:6379
      - NS_SERVER=loraserver:8000
      - JWT_SECRET="aaaa"
  redis:
    image: redis:3.0.7-alpine

  mqtt:
    image: eclipse-mosquitto:1.4.8
 
  postgres:
    build: ./pg
